#!/bin/bash

echo "all variables passed to script : $@"
echo "No.of variables passed : $#"
echo "first variable : $1"
echo "script name : $0"
echo "who is running : $USER"
echo "Which directory : $PWD"
echo "Present user Home directory : $HOME"
echo "PID of current script : $$"
sleep 5 &
echo "PID of background command runnign just now : $!"
wait $!
echo "line number : $LINENO"