#!/bin/bash
number1=10
number2=20

sum=$((number1+number2))
echo "sum of numbers is : $sum"

#ARRAY
MOVIES=("JAI BHIM" "VAKEELSAAB" "COURT") # INDEX always start from 0    
echo "movies are    : ${MOVIES[@]}"
echo "1st movie is  : ${MOVIES[$0]}"
echo "2nd movies is : ${MOVIES[$1]}"
echo "3rd movies is : ${MOVIES[$2]}"