#!/bin/bash
number1=10
number2=20

sum=$((number1+number2))
echo "sum of numbers is : $sum"

#ARRAY
MOVIES=("JAI BHIM" "VAKEELSAAB" "COURT") # INDEX always start from 0    
echo "All movie names are : ${MOVIES[@]}"
echo "1st Movies name :${MOVIES[0]}"
echo "2nd movie name  :${MOVIES[1]}"
echo "3rd movie name  :${MOVIES[2]}"